### PR TITLE
docs (flashing): Add WSON-8 for ADL laptops

### PR DESCRIPTION
**Pull request by leviport**

### CODE REVIEW

**Comment by crawfxrd** [comment]
Just drop "Laptops use a SOIC-8 package for the SPI flash ROM". It already directs users to `board_info.txt` to determine the chip and package.

A better place to document this would be the model-specific `README` along with the part number and location, or even tech-docs since it already has those.

This info is also added to the coreboot docs, such as: https://doc.coreboot.org/mainboard/system76/oryp8.html#flashing-coreboot. (But none of the ADL boards are currently merged.)

**Comment by leviport** [comment]
That's a fair point. It does seem a little confusing since each ADL-P variant also has its own `board_info.txt` that doesn't mention the package though. Users would have to know to check the `board_info.txt` in the `adl-p` directory instead. 

Do you think the part covering where pin 1 is located should stay in? Hopefully it's safe to assume that anyone embarking on the journey of external flashing would know how to find pin 1 already.

**Comment by crawfxrd** [comment]
> Do you think the part covering where pin 1 is located should stay in?

Yes.

> Hopefully it's safe to assume

There are probably people flashing for the first time who don't know what they're doing and just reading the doc.

**Review by crawfxrd — APPROVED** [review]

**Review by linuxgnuru — APPROVED** [review]

**Comment by crawfxrd** [comment]
commit message should be updated.

**Comment by leviport** [comment]
Squashed and updated

**Pull request merged**
