### PR TITLE
tgl: Update VBTs and GOP drivers

### PR DESCRIPTION
**Pull request by crawfxrd**
- Update Intel GOP driver to 17.0.1077
- Update VBT to 250

Test:

- Boot splash displays on screen
- Firmware setup menu is rendered, at correct resolution

Affects:

- [x] darp7
- [x] galp5
- [x] gaze16-3050
- [x] gaze16-3060
- [x] gaze16-3060-b
- [x] lemp10
- [x] oryp8

Requires: https://github.com/system76/coreboot/pull/223
Resolves: #525

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
Looks like gaze16-3060-b passes the test.

**Comment by XV-02** [comment]
Looks like oryp8 correctly displays the splash screen and firmware setup.

**Comment by XV-02** [comment]
Gaze16-3050 looks like it shows splash and setup as desired.

**Comment by XV-02** [comment]
Gaze16-3060 also looks good.

**Comment by XV-02** [comment]
Lemp 10 is behaving.

**Comment by jacobgkau** [comment]
It's behaving fine on darp7.

**Review by XV-02 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
