### PR TITLE
Add Galago Pro 6

### PR DESCRIPTION
**Pull request by crawfxrd**
- https://github.com/system76/coreboot/pull/129
- https://github.com/system76/ec/pull/293
  - https://github.com/system76/ec/pull/288
  - https://github.com/system76/ec/pull/296
  - https://github.com/system76/ec/pull/297
- https://github.com/system76/firmware-update/pull/64

### CODE REVIEW

**Comment by XV-02** [comment]
With all the components integrated, I'm seeing an issue with the combo-jack. It's not detecting a head-set being plugged in or prompting for the headset-headphone selection, nor do audio devices attached to the 3.5mm jack port showing up in sound settings. I grabbed a suite of logs:
[galp6-cbmem.txt](https://github.com/system76/firmware-open/files/9246142/galp6-cbmem.txt)
[galp6-dmesg.txt](https://github.com/system76/firmware-open/files/9246143/galp6-dmesg.txt)
[galp6-journal.txt](https://github.com/system76/firmware-open/files/9246144/galp6-journal.txt)

So far, other tests are looking good, though.

**Comment by crawfxrd** [comment]
Is the `master` staging branch added? Kernel should be [cb5f582](https://github.com/pop-os/linux/commit/cb5f582ee0af87703c91e492c23d13083804fa7b).

**Comment by crawfxrd** [comment]
Blocker: EC is turning on while system is off and unplugged (flashing orange).

**Comment by XV-02** [comment]
I'm seeing the flashing status light as well. Unsurprisingly, making sure the audio quirk is included resolved the audio issue.

**Review by XV-02 — APPROVED** [review]
This has passed our certification testing. https://github.com/system76/certification/blob/1fe8823e067a5dd1b997b1688461d9ff602bd324/laptops/galp6/03-08-2022-galp6-24f7604-Pop2204.md

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
