### PR TITLE
gaze16-3060: Add variant for I219-V GbE

### PR DESCRIPTION
**Pull request by crawfxrd**
system76/coreboot#84

### CODE REVIEW

**Comment by crawfxrd** [comment]
Currently fails with:

```
[    0.299486] pci 0000:00:1f.6: [8086:15fa] type 00 class 0x020000
[    0.299538] pci 0000:00:1f.6: reg 0x10: [mem 0x80620000-0x8063ffff]
[    0.299815] pci 0000:00:1f.6: PME# supported from D0 D3hot D3cold
[    0.865335] e1000e: Intel(R) PRO/1000 Network Driver
[    0.865338] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    0.865597] e1000e 0000:00:1f.6: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    1.341263] e1000e 0000:00:1f.6 0000:00:1f.6 (uninitialized): Failed to disable ULP
[    1.969470] e1000e: probe of 0000:00:1f.6 failed with error -2
```

Not sure if something in the IFD or coreboot needs to change.

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
Should  I convert gaze16-3060 to variants, for Intel and Realtek controllers?

**Comment by jackpot51** [comment]
@crawfxrd is it possible for the Realtek variant to boot with all the Intel variant changes?

**Comment by jackpot51** [comment]
I do think you should probably create a new variant, with a new DMI code, since probably it would be bad to enable the Intel ethernet device when it is not connected

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
