### PR TITLE
addw2, gaze15, and oryp6 support

### PR DESCRIPTION
**Pull request by jackpot51**
Depends on coreboot PR: https://github.com/system76/coreboot/pull/16
Depends on EC PR: https://github.com/system76/ec/pull/70

### CODE REVIEW

**Comment by jackpot51** [comment]
Touchpad interrupt is now fixed. Next I will try to get the NVIDIA GPU going.

**Comment by jackpot51** [comment]
NVIDIA GPU now loads. Hybrid graphics is not working yet

**Comment by cognifloyd** [comment]
With this change, does Hybrid graphics work with firmware-open on addw2, gaze15, and oryp6?

**Comment by jackpot51** [comment]
Hybrid graphics is working on the oryp6 and will work on the addw2 and gaze15 when changes are synced

**Pull request merged**
