### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by jackpot51**
This is mostly copied from the EC CI.

### CODE REVIEW

**Comment by crawfxrd** [comment]
I didn't want to do this because of how long I expect installing deps and setting up coreboot will take. If we had our own runners with at least crossgcc built we could cut down a lot of the time.

**Comment by ids1024** [comment]
It might be possible to improve that with GitHub Actions caching.

https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

**Comment by crawfxrd** [comment]
Caching would mean building it once per CI run, but you'd still be building it once. If we have them precompiled, it would cut out ~10 minutes from every run.

coreboot has a project idea to [provide the toolchain as precompiled packages](https://doc.coreboot.org/contributing/project_ideas.html#provide-toolchain-binaries) for distros. Something like that may be easier. Then we don't need to maintain a custom runner, just the crossgcc packages.

**Comment by jackpot51** [comment]
It is clear that GitHub cannot handle the extremely simple task of actually caching what it is asked to cache, so I guess I'm giving up on this

**Pull request closed without merging**
