### PR TITLE
for Arch Linux  

### PR DESCRIPTION
**Pull request by aram-hamo**

### CODE REVIEW

**Comment by aram-hamo** [comment]
this time the email should show up

**Comment by crawfxrd** [comment]
Can you edit the commit message to say it's for Arch Linux?

**Comment by aram-hamo** [comment]
done

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
I missed that @crawfxrd - I can rewrite the commit

**Comment by jackpot51** [comment]
Fixed the commit message

**Pull request merged**
