### PR TITLE
darp10: Add Darter Pro 10

### PR DESCRIPTION
**Pull request by crawfxrd**
- https://github.com/system76/coreboot/pull/219
- https://github.com/system76/ec/pull/451
- https://github.com/system76/firmware-update/pull/104

### CODE REVIEW

**Comment by XV-02** [comment]
I mentioned this in the [firmware issue](https://github.com/system76/firmware/pull/659) as well, as it looks to impact both that PR, as well as firmware built from this PR.

While certifying the system, it appears that HDMI is not functioning. *randr doesn't indicate the presence of a display and there is no evidence in logs of a connection being detected. Several monitors and cable were testing, suggesting it is an actual Darp10 issue.

**Comment by XV-02** [comment]
The HDMI is now correctly outputting.

However, I have run into the following issue around suspend/resume:
1) I have the laptop, with the lid open, before me.
2) I attach an HDMI display. Displays correctly adjust.
3) I boot the system with the external HDMI attached, such as a reboot after updates. 
4) After the new boot, I close the laptop lid. Displays correctly adjust.
5) I unplug the HDMI display. 
6) With lid closed, and no external display, the system correctly suspends. 
7) I attempt to open the lid. The system briefly resumes, but the display remains blank. The system suspends again shortly after. 

At this point, I have to fully power the system off to render it usable again. Reattaching the HDMI display does not help. 

Additional notes:
- This does not happen with displays attached over the Thunderbolt/DP connection.
- If the system is suspend with the lid closed and an HDMI display attached, and then resumed in that state by external keyboard input, there are no issues.
- If the system is suspend with the lid closed and an HDMI display, and then resumed by opening the laptop lid, there is no issue.
- If the system has an external HDMI display, and the lid closed; then the external display is removed, and the system suspends; and then the HDMI display is reattached: The system will correctly resume when woken with an external keyboard input.
- This only happens if the system is _booted_ with the HDMI display attached. If the display is attached post-hoc, then these issues are not present.

**Comment by XV-02** [comment]
Okay: While I can get the HDMI/Suspend-Resume issue to trigger in bursts, I cannot get it to trigger reliably. I had two bouts of it today though, so it is often enough to be a concern and hopefully to be able to diagnose. 

I believe it occurs when HDMI is attached at boot, but honestly, I do not remember what the condition was on the first tranche of times I saw the issue, though I know that attached-at-boot was the condition the second time.

The reason it concerns me is that users who use a Dual `internal + external` setup at a fixed location, like an office or home desk, are likely to close a laptop before unhooking it when transitioning to a on-the-move regime such as to give a presentation or to work from a remote location. There is a risk of hard data-loss with this problem as well, as any unsaved work may be readily lost - for example, unsynced log entries that would normally be written out on resume are lost  (which is annoy for diagnosing the issue).

**Comment by XV-02** [comment]
For the moment, I'm continuing other certification test:

@crawfxrd I'm having issues with ethernet not working. `lspci` reports `Ethernet controller: Intel Corporation Device 550a (rev 20)`

However, nothing else seems to see the presence of an ethernet device. `ip` only returns results for the `lo` and `wlp` device types, and at best utilities like `inxi` are showing that there is *something* but suggests the correct driver is not present, which I somewhat doubt, unless the driver support post-dates our current kernel. 

Any guidance on what to prod? I've harasses the sysfs entry fairly robustly, and I've confirmed that what appears to be the correct driver (the Intel `e1000e` driver) is present and loaded.

**Comment by crawfxrd** [comment]
The clock config is most likely wrong.

**Review by jackpot51 — APPROVED** [review]

**Review by XV-02 — APPROVED** [review]

**Pull request merged**
