### PR TITLE
Update coreboot and CSME

### PR DESCRIPTION
**Pull request by crawfxrd**
Update coreboot and switch boards to use public releases of blobs:

- TGL-U microcode: revision 0xa4
- TGL-H microcode: revision 0x3e
- ADL microcode: revision 0x41c
- ADL FSP: C.0.69.74

Update CSME for ADL and TGL:

- ADL-P: 16.0.15.1810v8 (16.0.15.1829)
- TGL-H: 15.0.41.2158
- TGL-U: 15.0.41.2158

I do not expect this to be tested for every board. One for each SoC would suffice for now. I will fix issues for boards as needed when I stage new releases for them.

- [ ] TGL-H
- [ ] TGL-U
- [ ] ADL-P

### CODE REVIEW

**Comment by crawfxrd** [comment]
All these laptops and I don't have a CML-U model to test on.

**Comment by crawfxrd** [comment]
Issues:

- gaze15: With new CSME, cannot boot if only RAM1 is filled (RAM2, and RAM1+RAM2 works)

**Comment by XV-02** [comment]
What are you using for diagnostics after you flash this?

**Comment by crawfxrd** [comment]
cbmem log and dmesg

**Comment by XV-02** [comment]
On `darp8` (ADL-P) I'm seeing a block of ACPI errors from dmesg - lines in the 430s of the attached file - and a couple of other errors in the mid 920s. 

[dmesg.txt](https://github.com/system76/firmware-open/files/9222956/dmesg.txt)

And nothing notable to me from cbmem.

[cbmem.txt](https://github.com/system76/firmware-open/files/9222957/cbmem.txt)

**Comment by crawfxrd** [comment]
The first 3 ACPI errors are caused by system76/coreboot@d8d522884bfbc. I don't know what causes the MCHC errors.

**Comment by XV-02** [comment]
Looking at the cbmem output, there's a block of warnings from ~650 - ~690, a handful ~1290, one at 1331 for `'fallback/slic' not found`, and some at ~1470. 

Only three flagged as errors at 415, 423, and 861.

[cbmem.txt](https://github.com/system76/firmware-open/files/9223691/cbmem.txt)

**Comment by crawfxrd** [comment]
The cbmem added is still the timing one, but I'm guessing those are the PCI device not found warnings which aren't an issue. `fallback/slic` doesn't cause any issues as well AFAIK. And  I think the errors would be something about GPIO pads and USB4? Those are normal based on the current release.

**Comment by crawfxrd** [comment]
I've removed the ACPI device names that are causing errors, so only the MCHC errors will be present.

**Comment by crawfxrd** [comment]
There's another new CSME release for ADL-P:

- ID: 738545
- Version: 16.1.25.1932

**Comment by crawfxrd** [comment]
I'm dropping the CSME update for CML. They still cause problems.

**Pull request closed without merging**
