### PR TITLE
Add oryp10

### PR DESCRIPTION
**Pull request by crawfxrd**
- https://github.com/system76/coreboot/pull/133
- https://github.com/system76/ec/pull/299
- https://github.com/system76/firmware-update/pull/66

### TODO

- [x] firmware-setup is *very* slow
  - Caused by blitting the entire 4k display; won't fix for this

### CODE REVIEW

**Comment by XV-02** [comment]
With the latest commit, I am not seeing correct functionality with the `turn off display` feature. It appears instead to be locking the machine as if passed `Super+Esc` instead of `Fn+F2` 

However, I don't believe it is just locking the session. The behaviour of locking and user-input prompting the session to unlock is different between using the lock shortcut and attempting to disable the display. The `Fn+F2` behaviour takes longer to recover from generally, though I think this might be tied to package c-states as it's significantly quicker to respond when running stress in the background. 

I'm also not seeing any journal logs indicating the system is suspending, so I think it's discreet from that as well.

An additional bug was that, is running stress while testing `Fn+F2`, upon return the screen exhibits a very noticeable flicker.

**Comment by crawfxrd** [comment]
OLED machines lock the display instead of turning it off. It's probably for some technical reason, but I don't know what it is.

**Comment by XV-02** [comment]
Good to know, vis-a-vis OLEDs not turning off. The flicker is still significant. 
Footage of the flickering behaviour. It take a reboot to clear the flickering

https://user-images.githubusercontent.com/98765732/187514498-94cb1e1e-f862-4574-b1cb-adfd3c799495.mp4

This flickering does not occur when using `Super+Esc`, only with `Fn+F2`

**Comment by crawfxrd** [comment]
Does it happen if you disable hidpi daemon in Displays?

**Comment by XV-02** [comment]
It does not persist with the HiDPI daemon disabled. On one test, the screen briefly flicked on the unlock prompt, but behaved as desired after logging in again. Otherwise, it does not occur without the HiDPI daemon.

**Comment by XV-02** [comment]
So far, most things are looking good. However, in both Hybrid and Nvidia mode, the decrypt prompt displays on the integrated screen even with the lid closed and an external (HDMI) display attached. Additionally, if the lid is opened and the decryption password provided, the system just hangs at a blank screen. 
Journal log from one of these boots
[Oryp10JournalLog.txt](https://github.com/system76/firmware-open/files/9457017/Oryp10JournalLog.txt)

**Comment by XV-02** [comment]
When entering and exiting suspend, there is a great variance in the time taken both to reach suspend, and to resume. 
While suspending, the process is usually quite quick, but seems to occasionally take upwards of 15 seconds. On resume, the process is generally somewhat slow (taking 10 or more seconds). This isn't blocking, but I wanted to note it.

However, the major worry is that the system seems to fail to resume successfully at times. Twice, while doing manual suspend tests, and both times on battery in hybrid mode, the system has suspended (or at least the status light has started flashing consistently with reaching suspend). On a keyboard input, the status light has returned to solid, though the screen has remained blank, and the system doesn't respond in any way I can detect to further inputs.

I've attached journalctl and dmesg outputs:
[Oryp10SuspendLog.txt](https://github.com/system76/firmware-open/files/9457133/Oryp10SuspendLog.txt)
[Oryp10SuspendDmesg.txt](https://github.com/system76/firmware-open/files/9457137/Oryp10SuspendDmesg.txt)

**Comment by crawfxrd** [comment]
What does addw2 do? External displays seem so broken with this panel.

**Comment by crawfxrd** [comment]
> So far, most things are looking good. However, in both Hybrid and Nvidia mode, the decrypt prompt displays on the integrated screen even with the lid closed and an external (HDMI) display attached.

NVIDIA drivers need to be added to the initramfs for it to show up on dGPU displays.

**Comment by crawfxrd** [comment]
Suspend is magically working for me now after the TBT change.

**Review by leviport — APPROVED** [review]
Approving for oryp9 updates, but further testing is required before oryp10 firmware release

**Pull request merged**
