### PR TITLE
darp7, galp5, lemp10

### PR DESCRIPTION
**Pull request by jackpot51**
Previous history is in tigerlake-preserve. Boards to check:

- addw2
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- bonw14
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- darp6 (with Proprietary EC)
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- darp7
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- galp4 (with Proprietary EC)
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- galp5
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- lemp9
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing
- lemp10
  - [x] compiles
  - [ ] boots
  - [ ] firmware PR
  - [ ] firmware testing
- oryp6
  - [x] compiles
  - [x] boots
  - [ ] firmware PR
  - [ ] firmware testing

Still unsupported but good to check:
- addw1
  - [x] compiles
  - [ ] boots
- darp5
  - [x] compiles
  - [ ] boots
- galp3-c
  - [x] compiles
  - [x] boots
- gaze15
  - [x] compiles
  - [ ] boots
- oryp5
  - [x] compiles
  - [ ] boots

### CODE REVIEW

**Comment by jackpot51** [comment]
Build is at https://buildchain.system76.com/job/firmware-open/36. This is ready to be tested, but you MUST be okay with getting a brick requiring an external programmer.

**Comment by crawfxrd** [comment]
oryp5 does not boot: appears to hang at boot splash. Keyboard does not work (have to use external USB keyboard to access firmware-setup). Drives are not populated in Boot Once. Using firmware-update produces the "App error: NotFound" issue. Will investigate more later.

**Comment by ids1024** [comment]
For some reason there doesn't seem to be a build artifact for gaze15 (while there are artifacts for the other unsupported models).

**Comment by jackpot51** [comment]
I think I left it out by accident

**Comment by jackpot51** [comment]
It will build on https://buildchain.system76.com/job/firmware-open/37/

**Comment by jackpot51** [comment]
Ooops, I did not choose the galp5 branch...

**Comment by jackpot51** [comment]
Ok, this is the real build: https://buildchain.system76.com/job/firmware-open/38

**Comment by jackpot51** [comment]
This is the real, real build: https://buildchain.system76.com/job/firmware-open/39/

**Comment by jacobgkau** [comment]
Getting this on gaze15 from build 39:

```
Press enter to commence flashing, the system may reboot...
Preserving boot order
bios: no flash implementation found
Restored boot order
BIOS Flash Error: 1
BIOS: Failure: DeviceError
Found boot override 0002
Removed boot override
Found boot order [0004, 2003, 0000, 2001, 2002]
Set boot order [0004, 2003, 0000, 2001, 2002]
Found boot option 2002
Removed boot option 2002
! Failed to apply updates !
Press any key to shutdown...
```

This is on a machine currently running proprietary firmware, but the USB is how we normally switch between proprietary/open, so I'd expect this to work. Let me know if it needs to be transitioned first.

**Comment by jackpot51** [comment]
@jacobgkau What firmware version is it running right now? If it is on proprietary, it will need to wait for the firmware blob PR before this works

**Comment by jacobgkau** [comment]
> @jacobgkau What firmware version is it running right now? If it is on proprietary, it will need to wait for the firmware blob PR before this works

It's currently on `1.07.11a`. I don't see a 76ec available in the firmware blobs right now, so I'll hold off on testing it.

**Comment by crawfxrd** [comment]
oryp5 is failing to read the SMM store after appending to it.

[debug.log](https://github.com/system76/firmware-open/files/5823686/debug.log)

**Pull request merged**
