### PR TITLE
Add Jenkinsfile for Pipeline

### PR DESCRIPTION
**Pull request by crawfxrd**
Ref: https://www.jenkins.io/doc/book/pipeline/
Ref: https://buildchain.system76.com/pipeline-syntax/

### TODO

- [x] Document required plugins
- [x] Add build parameter for git revision/branch
- [x] [Slack notifications](https://plugins.jenkins.io/slack/)?
  - Basic messages added
- [x] Build boards in a matrix to report each separately?
  - Must be sequential due to reusing workspace
- [x] Figure out how to test it
  - Set up a local instance
- [x] Add GitHub token to Jenkins

### CODE REVIEW

**Comment by crawfxrd** [comment]
It doesn't look like we have the GitHub plugin installed (I don't see it in the Snippet Generator). We currently set the status manually with a curl command.

**Comment by crawfxrd** [comment]
I set up a local Jenkins controller and agent and got this building.

One problem I'm having though is that it rebuilds every time it polls SCM.

**Comment by crawfxrd** [comment]
Parallel builds cannot be used with our current setup, as it would clobber the workspace.

coreboot has some Dockerfiles (`util/coreboot`) that could be used as a base to migrate to containerized builds. But then we would be building the edk2 payload for every model (it's the same binary for all laptops; only qemu builds it differently).

**Comment by crawfxrd** [comment]
I've added the GitHub token to the credentials manager.

So I think the only issue now is you can't convert an existing project to Pipeline; it has to be a new project?

**Review by 13r0ck — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Approving as I understand this will be used for a new Jenkins job which will replace the current `firmware-open` job.

My understanding is also that the benefit to converting from the current job to a pipeline would be having the job specified in code so it's version-controlled and reviewed like the rest of the repository.

The `Jenkinsfile` appears to match the current configuration of the Jenkins job in the Jenkins web UI.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
