### PR TITLE
The big one

### PR DESCRIPTION
**Pull request by crawfxrd**
- [Rebase coreboot on the 4.15 release](https://github.com/system76/coreboot/pull/80)
- [Rebase edk2 on the edk2-stable202108 release](https://github.com/system76/edk2/pull/34)
- Update Rust toolchain to nightly-2021-06-15

### Relevant issues

This change has the potential to affect most reported issues.

Resolves:

- system76/firmware-open#191
- system76/firmware-open#197
- system76/firmware-open#219
- system76/firmware-open#235
- system76/firmware-open#238
- system76/firmware-open#246
- system76/coreboot#77
- system76/ec#138

May address:

- system76/firmware-open#23
- system76/firmware-open#33
- system76/firmware-open#38
- system76/firmware-open#41
- system76/firmware-open#44
- system76/firmware-open#50
- system76/firmware-open#56
- system76/firmware-open#61
- system76/firmware-open#71
- system76/firmware-open#80
- system76/firmware-open#83
- system76/firmware-open#117
- system76/firmware-open#183
- system76/firmware-open#230

Unblocks:

- system76/firmware-open#111
- system76/firmware-open#225
- system76/firmware-open#227

Introduces:

- edk2 exception when booting signed binary

### TODO

- [x] Update Rust components to work with the new toolchain
  - [x] modeltool
  - [x] [ec](https://github.com/system76/ec/pull/253)
    - [x] ectool
    - [x] [ecflash](https://github.com/system76/ecflash/pull/3)
    - [x] [ecsim](https://github.com/system76/ecsim/pull/7)
    - [x] [ecspy](https://github.com/system76/ecspy/pull/1)
  - [x] [firmware-setup](https://github.com/system76/firmware-setup/pull/23)
    - `Serial` only used for debug feature: Hide warnings behind the cfg?
  - [x] [firmware-smmstore](https://github.com/system76/firmware-smmstore/pull/17)
  - [x] [firmware-update](https://github.com/system76/firmware-update/pull/46)
  - [x] [gop-policy](https://github.com/system76/gop-policy/pull/8)
  - [x] [intel-spi](https://github.com/system76/intel-spi/pull/3)
  - [x] [intelflash](https://gitlab.redox-os.org/redox-os/intelflash/-/merge_requests/5)
  - [ ] [orbclient](https://gitlab.redox-os.org/redox-os/orbclient/-/merge_requests/68): update `no_std` support?
  - [ ] [orbfont](https://gitlab.redox-os.org/redox-os/orbfont/-/merge_requests/5): update `no_std` support?
- [x] Remove `libs/smmstore` and replace it with `apps/firmware-smmstore/examples/read` in `scripts/smmstore.sh`
- [x] Fix NVIDIA GPU resource allocation in coreboot / skip aperture checks in edk2
- [x] Fix running firmware-setup in edk2
- [ ] [Add SMMSTOREv2 commands to firmware-smmstore](https://github.com/system76/firmware-smmstore/pull/8)
- [ ] [Update firmware-update to migrate SMMSTOREv1 data to SMMSTOREv2 data](https://github.com/system76/firmware-update/issues/48)
- [x] Write the changelog entry
- [x] Basic documentation
  - [x] CMOS option for IME
  - [x] Secure Boot status
- [ ] Update Jenkins
  - [x] Update Rust/install new toolchain to fix build
  - [x] Remove edk2 build cache before building all models
  - [ ] Use new coreboot GCC toolchain: 8.3 -> 11.2 (very last thing, since current coreboot branch fails to build with 11.2)

### CODE REVIEW

**Comment by crawfxrd** [comment]
Secure Boot will be disabled for this release. 9elements is working on a fix for something, and we need to decide on what and how info is going to be exposed in the firmware UI.

**Comment by crawfxrd** [comment]
This is now in a good state to start testing.

Besides fixing things that come up in testing, the only potential remaining task is to get firmware-update to [migrate the SMMSTORE data](https://github.com/system76/firmware-update/pull/51).

**Comment by jacobgkau** [comment]
Just to confirm (and get this on record in the PR), the addw2 still fails to boot to Pop!_OS with this update (both ddbffac that's built on the build server and 16bcdd9 built locally.) We'll take a look through some other NVIDIA machines to see if anything else is affected by the same issue.

**Comment by crawfxrd** [comment]
addw2 boot breakage has been fixed. The `MAX_CPUS` override was missing, causing MP init to fail.

Additionally, [coreboot measured boot](https://doc.coreboot.org/security/vboot/measured_boot.html) has been enabled on all models.

**Comment by nkalkhof** [comment]
Any ETA on a release for lemp10 or at least the option to build?

**Comment by jacobgkau** [comment]
> Any ETA on a release for lemp10 or at least the option to build?

You can build now using these commands:

```
git clone https://github.com/system76/firmware-open
cd firmware-open
git checkout the-big-one
./scripts/update.sh
./scripts/deps.sh
./scripts/build.sh lemp10
./scripts/flash.sh lemp10
```

If you didn't already have Rust installed, you may need to close and re-open your terminal after `deps.sh` in order to build. The `flash.sh` script will cause a reboot. Finally, this will not work on Pop!_OS 21.10 yet due to https://github.com/system76/firmware-open/issues/264.

There is not an ETA at this time.

**Comment by nkalkhof** [comment]
Thanks for the heads up. I'm using Pop! 21.10 on an external drive and Gentoo as daily driver. Any advice what OS/version to switch to in order to build coreboot?

**Comment by crawfxrd** [comment]
Known issue with the update: edk2 will throw an exception and hang when trying to boot a signed binary (e.g., using https://github.com/jackpot51/popcorn).

**Comment by 13r0ck** [comment]
@nkalkhof 
> Thanks for the heads up. I'm using Pop! 21.10 on an external drive and Gentoo as daily driver. Any advice what OS/version to switch to in order to build coreboot?

We only officially test on Pop!_OS, and recommend using the latest version of Pop!_OS for most users.
If you have any more questions please ask on our [Mattermost](https://chat.pop-os.org/)

**Comment by jacobgkau** [comment]
I installed 20.04 LTS on an oryp8, checked out this branch, and tried to build. The `update.sh` script stopped at trying to clone the modules inside of https://github.com/system76/coreboot/tree/system76/3rdparty. A manual `git submodule update --init --recursive` stops at the same place.

Screenshot from 2021-12-21 10-08-19

Looking at https://github.com/system76/coreboot/tree/system76/3rdparty, I can't click on any of those submodules even when I'm logged into the GitHub web interface. Is it expected to fail past all of these submodules when updating?

**Comment by crawfxrd** [comment]
Updated the coreboot submodules to use absolute paths. Fresh checkouts will work now.

**Review by jacobgkau — APPROVED** [review]
78c1dfd builds and flashes on oryp8. Approving so we can merge this; full regression testing will be done on each model before the updates are released through the firmware updater.

**Review by jackpot51 — APPROVED** [review]

**Comment by ZeddieXX** [comment]
Does this mean everything is fixed now?  Can I update my firmware through the normal way it do I still need to clone this and compile?

If I still need to compile, what are the steps to clone, compile, and flash?  Again I'm not a dev so I'll need step by step instructions.

Thanks!

**Comment by nkalkhof** [comment]
> 

S76 support told me that there is no ETA for this new coreboot release so I compiled and flashed coreboot from system76 main branch approx two weeks ago on my lemp10 omitting the EC since I have an altered fan table. Had to unplug my CMOS battery to clear after flashing. After that everything seems to work including TBT4 and IME toggle.
Howevwer if you follow the latest issues it becomes clear that there the current codebase is still a litte rough around the edges. So if you are not in a hurry I'd recommend to wait. If you cannot wait there is a pretty straight forward documentation on how to proceed [https://github.com/system76/firmware-open](https://github.com/system76/firmware-open).

**Comment by ZeddieXX** [comment]
Thanks.  Is there a list of issues left?  I want to see if it will affect my use case before I compile and flash.  Right now I haven't really been able to use my GALP5 because of the current issues of the boot entries being deleted every cold boot.  I just left it on and using it as a "server".  I would love to use it as a laptop again.

So wondering if the rough edges are still better than what I have now.

Thanks.

**Comment by jacobgkau** [comment]
@ZeddieXX The list of known issues would be the repo's issue list: https://github.com/system76/firmware-open/issues 

There may be further issues that are yet unknown, which is why the update hasn't been pushed out to all models yet.

We are very close to releasing the update on lemp10-- https://github.com/system76/firmware-open/issues/269 was a last-minute showstopper. oryp8 is having some NVIDIA-related issues, and while galp5 NVIDIA doesn't appear to be affected, I'm not sure if the changes to oryp8 will result in changes to galp5 as well.

If you don't want to wait for the update to be tested and released, you are welcome to just flash and try it yourself. If you want other people to try it for you first, then you'll have to wait for that to happen. The commands to build and flash are the same ones I provided [earlier in this PR](https://github.com/system76/firmware-open/pull/260#issuecomment-996014209):

```
git clone https://github.com/system76/firmware-open
cd firmware-open
./scripts/update.sh
./scripts/deps.sh
./scripts/build.sh galp5
./scripts/flash.sh galp5
```

The only difference is not checking out any branch since this branch has now been merged.

**Comment by ethuleau** [comment]
Hi @nkalkhof, why and how did you altered your lemp10 fan table? Did you do that to be smoother?

**Comment by nkalkhof** [comment]
> Hi @nkalkhof, why and how did you altered your lemp10 fan table? Did you do that to be smoother?

The fan curve is badly adjusted on the lemp10 in the 60-70°C range IMHO. I've adjusted the fan curve to let the fan kick in as soon as the package temperature trips 60°C. The fan then runs at very quiet ~2500RPM until the temperature drops below 55°C. This helps to keep the temperatures and the suddenly occuring fan noise in check. I still have some hope that S76 will offer a userspace adjustable option sometime in the future *wink*.

These are my changes (lemp10):
Add
CFLAGS+=-DBOARD_HEATUP=5 CFLAGS+=-DBOARD_COOLDOWN=20 CFLAGS+=-DBOARD_FAN_POINTS="
FAN_POINT(60, 30),
FAN_POINT(70, 40),
FAN_POINT(75, 50),
FAN_POINT(80, 60),
FAN_POINT(85, 65),
FAN_POINT(90, 65)" 

to firmware-open/ec/src/board/system76/lemp10/board.mk and flash EC according to the instructions found in firmware-open git. Do this at your own risk!!!

**Comment by gabcoh** [comment]
Is there any way we can monitor when the newest version of the firmware is released? Will it be announced somewhere or is the latest released version tracked somewhere? I've got a lemp10 and I'm having trouble with #246 and just want to make sure I get the update as soon as I can (without risking bricking my laptop and installing the firmware myself).

**Comment by ZeddieXX** [comment]
When I try to flash, I get this error:
  --- stderr
  thread 'main' panicked at 'Unable to find hidapi-hidraw: `"pkg-config" "--libs" "--cflags" "hidapi-hidraw"` did not exit successfully: exit status: 1
  --- stderr
  Package hidapi-hidraw was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hidapi-hidraw.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hidapi-hidraw' found
  ', /home/zeddie/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.7/build.rs:78:60
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by crawfxrd** [comment]
Run `./ec/scripts/deps.sh` to install the missing deps.

**Comment by ZeddieXX** [comment]
Thanks.   but now I'm getting:
zeddie@zedlin-galp5:~/temp/firmware-open$ ./scripts/flash.sh galp5
    Finished release [optimized] target(s) in 0.00s
SPI HSFSTS_CTL: WRSDIS | FDOPSS | FDV | FLOCKDN
SPI FILE: Loadingthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:68:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zeddie@zedlin-galp5:~/temp/firmware-open$

**Comment by ZeddieXX** [comment]
I'm going to run build.sh again, then try flashing again now that I ran the ./ec/scripts/deps.sh

**Comment by ZeddieXX** [comment]
That worked!  Hopefully the issue with the missing EFI boot entries is fixed.  Right now I'm trying out Fedora 35, no other OSes, so I probably wont be able to find out if the issue is fixed until I can shrink the partition and install a dual-boot Windows.

**Comment by ZeddieXX** [comment]
Hi.  I still noticed the newest available firmware is still 2021-07-20_93C2809 for my galp5.  When will a new firmware be released into the official update channel?

I just compiled and flashed the current one (2022-07-27_7e4a92c).  Is there other bugs that's preventing a new firmware release for the galp5?  It's been over a year and the latest available firmware in the official update channel didn't incorporate this merge (The big one).

**Comment by crawfxrd** [comment]
I am finishing up the Alder Lake boards, then will be making releases for previous generations.

I should be able to start making RCs next week.

**Comment by ZeddieXX** [comment]
Hi @crawfxrd .  Any updates on RCs for GALP5?  Still says 2021-07-20_93c2809 is the latest.

The last time I downloaded and compiled, I got the 2022-07-27_7e4a92c and I am still contstantly getting "new firmware update available" notifications even though I have a newer build.

Maybe a good idea to prevent Settings of false new firmware notifications if the built version is newer than what's offered in RC.

**Comment by jacobgkau** [comment]
> I am still contstantly getting "new firmware update available" notifications even though I have a newer build.

You can disable those multiple ways!

Option 1: open Startup Apps and un-check `Firmware Manager Check`. This will not prevent Settings from working, but would need to be done on every user account individually.

Option 2: disable & stop `system76-firmware-daemon.service`. This will prevent Settings from manually checking for updates, but it will take effect for all users at once. You'll need to enable/start it again next time you want to check for updates.

```
sudo systemctl disable --now system76-firmware-daemon.service
sudo systemctl enable --now system76-firmware-daemon.service
```

(Tim can chime in on where we're at with a new release, but just going off of my knowledge, he's fixed some of the USB-C suspend issues, but some Thunderbolt suspend issues remain and have potentially gotten worse by being more exposed. There are also SSD issues he was working on fixing for lemp10 & darp7, although galp5 may have been less affected by those since it only has one SSD slot and no SATA support.)

> Maybe a good idea to prevent Settings of false new firmware notifications if the built version is newer than what's offered in RC.

The one corner case this raises off the top of my head would be no longer allowing rollbacks (which we have had to do because of some of the issues that have prevented releases for a while). If a version is pulled, users who have already upgraded would not be prompted to downgrade, so rolling back would require adding a new version to the changelog just for the rollback (which I can see an argument for doing.) It would allow people who like to customize their fan curves, etc. to still receive update notifications, which would be nice. And it shouldn't be too difficult considering our versioning scheme.

**Comment by ZeddieXX** [comment]
Thanks for the update.  I disabled in the Startup App since I'm the only user.  Since it's been yet another month, any updates on an official release for the galp5 yet?

I'm currently on 2022-07-27_7e4a92c (I compiled and flashed myself).  Anything I need to look out for if I compile and flash from the current main branch?

Thanks.  Also looking forward to your Rust-based Cosmic DE. :)

**Pull request merged**
