### PR TITLE
gaze15: Add ELAN touchpad settings

### PR DESCRIPTION
**Pull request by jackpot51**
This may address https://github.com/system76/firmware-open/issues/129. First functionality of systems with Synaptics touchpad should be verified. Then I will produce USB images for the affected users to try. Includes and requires https://github.com/system76/coreboot/pull/58

**Please provide `dmesg` output before and after installing!**

- Download [gaze15-touchpad.zip](https://github.com/system76/firmware-open/files/6172736/gaze15-touchpad.zip)
- Extract `gaze15-touchpad.img`
- Use Popsicle to flash to a USB drive
- Boot from the USB drive and follow the instructions to flash the firmware

### CODE REVIEW

**Comment by bflanagin** [comment]
Pop 20.10:
No adverse affects on my unit.

[dmesg-preELAN-output.txt](https://github.com/system76/firmware-open/files/6172549/dmesg-preELAN-output.txt)
[dmesg-PostELAN-output.txt](https://github.com/system76/firmware-open/files/6172550/dmesg-PostELAN-output.txt)

**Comment by jacobgkau** [comment]
I'm getting an error trying to flash from proprietary with the provided USB image:
IMG_20210319_101928
I've tried re-downloading the image and re-flashing the flash drive.

**Comment by jackpot51** [comment]
@jacobgkau thanks, I will make a new ZIP file with FPT included

**Comment by jackpot51** [comment]
@jacobgkau please try the ZIP file again, now the link should be https://github.com/system76/firmware-open/files/6172736/gaze15-touchpad.zip

**Comment by jacobgkau** [comment]
Working now (17" 1650.) The touchpad is still working normally.
[dmesg-proprietary.txt](https://github.com/system76/firmware-open/files/6172822/dmesg-proprietary.txt)
[dmesg-open-new.txt](https://github.com/system76/firmware-open/files/6172823/dmesg-open-new.txt)

**Comment by ids1024** [comment]
On my 1650 15" gaze15, it flashed fine and the touchpad is still working, as it did with the previous firmware.

[dmesg1.log](https://github.com/system76/firmware-open/files/6172947/dmesg1.log)
[dmesg2.log](https://github.com/system76/firmware-open/files/6172948/dmesg2.log)

**Pull request merged**
