### PR TITLE
qemu: Enable KVM

### PR DESCRIPTION
**Pull request by crawfxrd**
Fixes performance issues when running a QEMU VM.

Resolves: #299

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Getting this when running `qemu.sh` after the change:
```
jacob@serw12:~/Work/firmware-open$ ./scripts/qemu.sh 
ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
qemu-system-x86_64: failed to initialize kvm: Device or resource busy
```
Is more setup required now?

**Comment by jacobgkau** [comment]
Oh, it works after I closed VirtualBox. Is it expected to not be able to run this at the same time as other virtual machines? I would kind of expect multiple VM managers to work at once, but I guess I don't do that often.

**Comment by crawfxrd** [comment]
VirtualBox and KVM are different hypervisors. Only one can access the virtualization extensions at a time, so you can only run multiple VMs if they use the same hypervisor.

**Review by jacobgkau — APPROVED** [review]
This does improve the performance significantly.

**Pull request merged**
