### PR TITLE
WIP: disable ME on galp5 and lemp10

### PR DESCRIPTION
**Pull request by jackpot51**
This disables the ME on the galp5 and lemp10. This will also make S0iX not function properly.

Extract .img file, flash to a USB flash drive with Popsicle, and then boot from the USB flash drive to flash the firmware.
[galp5-disable-me.zip](https://github.com/system76/firmware-open/files/6728054/galp5-disable-me.zip)
[lemp10-disable-me.zip](https://github.com/system76/firmware-open/files/6728055/lemp10-disable-me.zip)

### CODE REVIEW

**Comment by salkdmaslkdm** [comment]
Questions i got:
How to build the every new bios by my self (step by step)? Like this image is build?
Can i flash this bios even i updates to a newer official bios?

Discovered Bugs:
- When you shut down the system the keyboard is still on, backlight and power light. You need an extra step to shut down. Press the power button after the Screen is black and only keyboard and power led are shining.

**Comment by jeanlucmongrain** [comment]
One of the main reason I bought a `lemp10` was to disable the Mossad backdoor.

It look that I can't do that without breaking sleep mode :(

**Comment by MrZenGit** [comment]
My first time using a System76 and working through an issue!  It worked, thank you.  Now I keep receiving notification that updates are ready for me to install.  I accidentally clicked it once and it undid the DISABLE back to normal.  How do I remove this from happening and how often will I have to do this?

What is the function of this "S0iX"?  I'm trying to learn quickly what about these terms.

Thank you again!

**Comment by crawfxrd** [comment]
This can be set at runtime by the `me_state` CMOS option.

**Pull request closed without merging**
