### PR TITLE
adding archlinux support

### PR DESCRIPTION
**Pull request by aram-hamo**

### CODE REVIEW

**Comment by crawfxrd** [comment]
Please author commits using real names and addresses.

**Comment by aram-hamo** [comment]
that's my real name !

**Comment by jackpot51** [comment]
@aram-hamo Your email isn't a usable one, when I look at it with git it shows up like this:

```
Author: Aram Hamo <35272300+aram-hamo@users.noreply.github.com>
Date:   Wed Mar 24 11:47:19 2021 +0100

    Update deps.sh
```

We need real emails to ensure if there are licensing issues that we can reach all contributors

**Comment by jackpot51** [comment]
This might be related to how you created the PR, was it on a public fork of this repository? If so, can you point to the commit there?

**Comment by aram-hamo** [comment]
ok thanks, i gonna try again with my real E-Mail

**Pull request closed without merging**
