### PR TITLE
Update RPL FSPs to 4221.00

### PR DESCRIPTION
**Pull request by crawfxrd**
Update the FSPs for:

- Raptor Lake P/H/PX/U
  - Version: 4221.00
  - ID: 781590
- Raptor Lake S/HX
  - Version: 4221.00
  - ID: 781583

This is the version Intel used for the most recent upstream coreboot changes.

As part of this, FSPs are now moved to `fsp/<soc>/<version>` instead of being in an arbitrary model's directory. All symlinks have been updated to point to the new locations.

Ref: Intel Software Kit ID 686654
Ref: https://review.coreboot.org/c/coreboot/+/76147

---

TEST

- [x] Compilation of all models works with coreboot `system76-4.19`
- [x] Compilation of all models works with coreboot `master`
- [ ] RPL models still boot
  - [ ] addw3
  - [ ] bonw15
  - [x] darp9
  - [x] galp7
  - [ ] gaze18
  - [ ] lemp12
  - [ ] oryp11
  - [ ] serw13

### CODE REVIEW

**Comment by crawfxrd** [comment]
This fixes compilation failures due to missing symbols when compiling with upstream coreboot, but it still fails due to `-Wmissing-include-dirs` in `Makefile.inc`.

**Comment by crawfxrd** [comment]
Either have to revert [CB:70251](https://review.coreboot.org/c/coreboot/+/70251) or change all the `coreboot.config`s to treat `FSP_HEADER_PATH` as relative to `coreboot`.

**Comment by crawfxrd** [comment]
With the FSP submodule removed, should I also move FSPs into a new `FSP/` directory instead of having them arbitrarily in one of the models?

**Comment by jackpot51** [comment]
> With the FSP submodule removed, should I also move FSPs into a new `FSP/` directory instead of having them arbitrarily in one of the models?

Sure

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
Rebase on coreboot 4.22 (#501) uses FSP releases from https://github.com/intel/fsp.

**Pull request closed without merging**
